---
title: "RNA-seq QC - All individuals"
author: "Quentin Miagoux"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: united
    highlight: tango
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
    css: "../my_css.css"
params:
  expr_xlsx: ""
  coldata_xlsx: ""
  top_variable_genes: 500
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.height = 8,
  fig.width = 10
)
```

```{r packages}
library("openxlsx")
library("tidyverse")
library("DESeq2")
library("matrixStats")
library("pheatmap")
library("viridis")
```

# Data loading

```{r load-data}
stopifnot(file.exists(params$expr_xlsx))
expr <- openxlsx::read.xlsx(params$expr_xlsx)

counts <- expr %>%
  dplyr::select(gene_symbol, starts_with("read_count_")) %>%
  mutate(across(-gene_symbol, as.numeric)) %>%
  mutate(across(-gene_symbol, round))

rownames(counts) <- counts$gene_symbol
counts <- counts[, -1, drop = FALSE]
counts_mat <- round(as.matrix(counts))
storage.mode(counts_mat) <- "integer"

colnames(counts_mat) <- colnames(counts_mat) %>%
  str_remove("^read_count_") %>%
  str_replace("^DNM2_", "DNMII")

counts_mat <- counts_mat[, str_detect(colnames(counts_mat), "^(DMD|WT|DN|LMNA|GSDII|DNMII)")]

ord <- order(as.integer(sub("^.*_", "", colnames(counts_mat))))
counts_mat <- counts_mat[, ord]

colnames(counts_mat) <- colnames(counts_mat) %>%
  sub("[0-9]+_", "_", .) %>%
  str_remove("_")
colnames(counts_mat) <- paste0(colnames(counts_mat), "_", rep(c(1, 2, 3)))


coldata <- tibble(samples = colnames(counts_mat)) %>%
  mutate(
    condition = sub("[0-9].*$", "", samples),
    condition_key = str_split(samples, "_", simplify = TRUE)[, 1]
  )

if (file.exists(params$coldata_xlsx)) {
  info <- openxlsx::read.xlsx(params$coldata_xlsx)
  if ("Dreams" %in% colnames(info)) {
    coldata <- coldata %>%
      left_join(info, by = c("condition_key" = "Dreams"))
  }
}

coldata_df <- as.data.frame(coldata)
rownames(coldata_df) <- coldata_df$samples
```

# VST transformation

```{r vst}
dds <- DESeqDataSetFromMatrix(
  countData = counts_mat,
  colData = coldata_df,
  design = ~1
)

dds <- dds[rowSums(counts(dds)) > 10, ]
vsd <- vst(dds, blind = TRUE)
```

# QC {.tabset .tabset-fade}

```{r pca-setup}
ntop_all_genes <- nrow(assay(vsd))

pca_all <- plotPCA(
  vsd,
  intgroup = c("samples", "condition"),
  returnData = TRUE,
  ntop = ntop_all_genes
)
percent_var_all <- round(100 * attr(pca_all, "percentVar"))

pca_all <- pca_all %>%
  mutate(samples = str_split(samples, "_", simplify = TRUE)[, 1])

pca_top <- plotPCA(
  vsd,
  intgroup = c("samples", "condition"),
  returnData = TRUE,
  ntop = 500
)
percent_var_top <- round(100 * attr(pca_top, "percentVar"))

pca_top <- pca_top %>%
  mutate(samples = str_split(samples, "_", simplify = TRUE)[, 1])

ann <- coldata_df %>%
  select(any_of(c("condition", "condition_key")))

rb_palette <- colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)

samples_to_exclude <- c("WT3", "DMD9")
keep_samples <- !(coldata_df$condition_key %in% samples_to_exclude)
vsd_filtered <- vsd[, keep_samples]
ann_filtered <- ann[keep_samples, , drop = FALSE]

pca_all_filtered <- plotPCA(
  vsd_filtered,
  intgroup = c("samples", "condition"),
  returnData = TRUE,
  ntop = nrow(assay(vsd_filtered))
)
percent_var_all_filtered <- round(100 * attr(pca_all_filtered, "percentVar"))

pca_all_filtered <- pca_all_filtered %>%
  mutate(samples = str_split(samples, "_", simplify = TRUE)[, 1])

pca_top_filtered <- plotPCA(
  vsd_filtered,
  intgroup = c("samples", "condition"),
  returnData = TRUE,
  ntop = 500
)
percent_var_top_filtered <- round(100 * attr(pca_top_filtered, "percentVar"))

pca_top_filtered <- pca_top_filtered %>%
  mutate(samples = str_split(samples, "_", simplify = TRUE)[, 1])
```

## All individuals {.tabset .tabset-fade}

### All genes

#### PCA

```{r pca-all-genes}
ggplot(pca_all, aes(PC1, PC2, color = samples)) +
  geom_point(size = 5, alpha = 0.8) +
  scale_shape_manual(values = 16:22) +
  scale_color_viridis_d(option = "turbo") +
  labs(
    title = "PCA (all genes)",
    x = paste0("PC1: ", percent_var_all[1], "% variance"),
    y = paste0("PC2: ", percent_var_all[2], "% variance")
  ) +
  coord_fixed(ratio = 4 / 3) +
  theme_bw()
```

#### Heatmap

```{r heatmap-all-genes}
sample_dist <- dist(t(assay(vsd)))
sample_dist_mat <- as.matrix(sample_dist)

pheatmap(
  sample_dist_mat,
  annotation_col = ann,
  annotation_row = ann,
  fontsize_col = 9,
  fontsize_row = 9,
  color = rb_palette,
  main = "Sample distances (all genes)"
)
```

### Top 500 variable genes

#### PCA

```{r pca-top-genes}
ggplot(pca_top, aes(PC1, PC2, color = samples)) +
  geom_point(size = 5, alpha = 0.8) +
  scale_shape_manual(values = 16:22) +
  scale_color_viridis_d(option = "turbo") +
  labs(
    title = "PCA (top 500 variable genes)",
    x = paste0("PC1: ", percent_var_top[1], "% variance"),
    y = paste0("PC2: ", percent_var_top[2], "% variance")
  ) +
  coord_fixed(ratio = 4 / 3) +
  theme_bw()
```

#### Heatmap

```{r heatmap-top-genes}
top_n <- params$top_variable_genes
vars <- matrixStats::rowVars(assay(vsd))
top_genes <- order(vars, decreasing = TRUE)[seq_len(min(top_n, length(vars)))]
vsd_top <- vsd[top_genes, ]

mat_top <- assay(vsd_top)
mat_top <- mat_top - rowMeans(mat_top)

pheatmap(
  mat_top,
  annotation_col = ann,
  show_rownames = FALSE,
  fontsize_col = 9,
  scale = "row",
  clustering_distance_rows = "correlation",
  clustering_distance_cols = "correlation",
  color = rb_palette,
  main = paste0("Heatmap (top ", top_n, " variable genes)")
)
```

## Without WT3 and DMD9 {.tabset .tabset-fade}

### All genes

#### PCA

```{r pca-all-genes-no-wt3-dmd9}
ggplot(pca_all_filtered, aes(PC1, PC2, color = samples)) +
  geom_point(size = 5, alpha = 0.8) +
  scale_shape_manual(values = 16:22) +
  scale_color_viridis_d(option = "turbo") +
  labs(
    title = "PCA (all genes, without WT3 and DMD9)",
    x = paste0("PC1: ", percent_var_all_filtered[1], "% variance"),
    y = paste0("PC2: ", percent_var_all_filtered[2], "% variance")
  ) +
  coord_fixed(ratio = 4 / 3) +
  theme_bw()
```

#### Heatmap

```{r heatmap-all-genes-no-wt3-dmd9}
sample_dist_filtered <- dist(t(assay(vsd_filtered)))
sample_dist_mat_filtered <- as.matrix(sample_dist_filtered)

pheatmap(
  sample_dist_mat_filtered,
  annotation_col = ann_filtered,
  annotation_row = ann_filtered,
  fontsize_col = 9,
  fontsize_row = 9,
  color = rb_palette,
  main = "Sample distances (all genes, without WT3 and DMD9)"
)
```

### Top 500 variable genes

#### PCA

```{r pca-top-genes-no-wt3-dmd9}
ggplot(pca_top_filtered, aes(PC1, PC2, color = samples)) +
  geom_point(size = 5, alpha = 0.8) +
  scale_shape_manual(values = 16:22) +
  scale_color_viridis_d(option = "turbo") +
  labs(
    title = "PCA (top 500 variable genes, without WT3 and DMD9)",
    x = paste0("PC1: ", percent_var_top_filtered[1], "% variance"),
    y = paste0("PC2: ", percent_var_top_filtered[2], "% variance")
  ) +
  coord_fixed(ratio = 4 / 3) +
  theme_bw()
```

#### Heatmap

```{r heatmap-top-genes-no-wt3-dmd9}
top_n <- params$top_variable_genes
vars <- matrixStats::rowVars(assay(vsd_filtered))
top_genes <- order(vars, decreasing = TRUE)[seq_len(min(top_n, length(vars)))]
vsd_top <- vsd_filtered[top_genes, ]

mat_top <- assay(vsd_top)
mat_top <- mat_top - rowMeans(mat_top)

pheatmap(
  mat_top,
  annotation_col = ann_filtered,
  show_rownames = FALSE,
  fontsize_col = 9,
  scale = "row",
  clustering_distance_rows = "correlation",
  clustering_distance_cols = "correlation",
  color = rb_palette,
  main = paste0("Heatmap (top ", top_n, " variable genes, without WT3 and DMD9)")
)
```
